name: .NET MAUI Master

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'NoteTakingApp.Maui/**/*'
      - '.github/workflows/master_maui.yml' 

defaults:
  run:
    shell: pwsh

env:
  PROJECT_PATH: "NoteTakingApp.Maui/NoteTakingApp.Maui.csproj"
  DOTNET_VERSION: "8.0.x"
  TELERIK_NUGET_KEY: ${{secrets.NUGET_KEY}}
  NUGETCONFIG_PATH: "nuget.config"

jobs:
# ******************************************************************************************************** #
#                                    >>>>>>> Windows build <<<<<<<                                         #
# ******************************************************************************************************** #
  maui-windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    # Needed for WinUI builds
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.2

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build Maui WinUI project
      run: dotnet build ${{env.PROJECT_PATH}} -c Debug -f net8.0-windows10.0.19041.0 -p:PublishTrimmed=False


# ******************************************************************************************************** #
#                                     >>>>>>> Android build <<<<<<<                                        #
# ******************************************************************************************************** #
  maui-android:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build Maui Android project
      run: dotnet build ${{env.PROJECT_PATH}} -c Debug -f net8.0-android -p:PublishTrimmed=False


# ******************************************************************************************************** #
#                                       >>>>>>> iOS Build <<<<<<<                                          #
# ******************************************************************************************************** #
  maui-ios:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #- uses: maxim-lobanov/setup-xcode@v1
    #  with:
    #    xcode-version: latest

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    - name: Build MAUI iOS project
      run: dotnet build ${{env.PROJECT_PATH}} -c Debug -f net8.0-ios -p:PublishTrimmed=True -p:MtouchLink=SdkOnly


# ******************************************************************************************************** #
#                                  >>>>>>> MacCatalyst Build <<<<<<<                                       #
# ******************************************************************************************************** #
  maui-macos:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #- uses: maxim-lobanov/setup-xcode@v1
    #  with:
    #    xcode-version: latest

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}
    
    - name: Build MAUI MacCatalyst project
      run: dotnet build ${{env.PROJECT_PATH}} -f net8.0-maccatalyst -c Debug -p:PublishTrimmed=True -p:MtouchLink=SdkOnly