name: Buid Winforms Project

on:
  workflow_dispatch:   # this means you can manually trigger it from the github UI
  push:  # This tells GitHub to watch for commits
    branches:
      - master # but ONLY commits to the master branch
    paths:  # this says to only run the workflow if there were updates to certain files or folders
      - 'NoteTakingApp/**/*'   # if any changes are in the project folder 
      - '.github/workflows/master.yml'  # if there are any changes to the workflow

jobs:
  # name of the job
  build_desktop_app:
    runs-on: windows-latest   # WinForms apps must be built on Windows runners
    
    # steps for the job to do
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    # install the .NET * SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    # Because this is a WinDForms app, there is an extra step of also adding msbuild.exe
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.2
    
    # now we can build the code
    - name: Build the WinForms application in "Release" mode and targeting 64 bit Windows OS
      run: msbuild NoteTakingApp\NoteTakingApp.csproj /t:Restore /p:Configuration=Release /p:RuntimeIdentifier=win-x64
