name: .NET MAUI Release

# We can trigger this workflow by...
on:
  # Optino 1 - A manual trigger inthe GitHub UI
  workflow_dispatch:
  # Option 2 - pushing to the maui-release branch
  push:
    branches:
      - maui-release

# Permissions for Azure CLI login using OIDC and publishing a GitHub Release
permissions:
  id-token: write
  contents: write
  discussions: write

env:
  PROJECT_PATH: "NoteTakingApp.Maui/NoteTakingApp.Maui.csproj"
  NUGETCONFIG_PATH: "nuget.config"
  BUILD_CONFIG: Release
  TFM: net8.0
  MACOS_ARTIFACTS_PATH: "artifacts_macos"
  IOS_ARTIFACTS_PATH: "artifacts_ios"
  ANDROID_ARTIFACTS_PATH: "artifacts_android"
  WINDOWS_ARTIFACTS_PATH: "artifacts_windows"
  TELERIK_NUGET_KEY: ${{secrets.NUGET_KEY}}

jobs:
# ***************************** #
# >>>>>>> Windows Build <<<<<<< #
# ***************************** #
  maui-windows:
    runs-on: windows-2022
    # Matrix! This is new for you, a matrix lets you run the same job, but in pultiple parallel passes; once for each 'store' or 'sideload' matrix
    strategy:   
      matrix:
        target_audience: [msstore, sideload]
    steps:
    - name: COMMON - Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: COMMON - Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # For WinUI builds
    - name: COMMON - Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.2    
      
    # This generates a unique version number using the date and the workflow run number (e.g. 2022.0314.1.0)
    - name: COMMON - Generate version number using date and run number
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $runNumber = "$env:GITHUB_RUN_NUMBER"
        $ver = $buildDay + "." + $runNumber + ".0"
        echo "APP_VERSION=$ver" >> $env:GITHUB_OUTPUT

    # The hosted runners do not have the maui workload installed by default, so we need to install it
    - name: COMMON - Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    # Restore NuGet packages ahead of time because we want to use the dedicated nuget.config file
    - name: COMMON - Restore NuGet packages
      shell: pwsh
      run: dotnet restore ${{env.PROJECT_PATH}} --configfile ${{env.NUGETCONFIG_PATH}}

    # ----------------------------------------------------------- #
    #               MICROSOFT STORE MATRIX STEPS                  #
    #           if matrix.target_audience == 'msstore'            #
    # ----------------------------------------------------------- #
    
    # Update the manifest for Microsoft Store identity
    - name: STORE - Update manifest for Microsoft Store build
      if: ${{matrix.target_audience}} == 'msstore'
      run: |
        [xml]$manifest = get-content 'NoteTakingApp.Maui\Platforms\Windows\Package.appxmanifest'
        $manifest.Package.Identity.Version = "${{steps.version-creator.outputs.APP_VERSION}}"
        $manifest.Package.Identity.Name = 'scottware.NoteTaker'
        $manifest.Package.Identity.Publisher = 'CN=63DAA465-AC12-4F45-960F-1C6EC865C821'
        $manifest.Package.Properties.DisplayName = 'NoteTake_r'
        $manifest.Package.Properties.PublisherDisplayName = 'scottware'
        $manifest.Package.Applications.Application.VisualElements.DisplayName = 'NoteTake_r'
        $manifest.save("NoteTakingApp.Maui\Platforms\Windows\Package.appxmanifest")

    # Compile and publish the WinUI project for the Microsoft Store (no code signing)
    - name: STORE - Build Maui WinUI project
      if: ${{matrix.target_audience}} == 'msstore'
      shell: pwsh
      run: dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f "${{env.TFM}}-windows10.0.19041.0" -p:RuntimeIdentifierOverride=win10-x64 -p:PublishTrimmed=False -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=false -p:EnableMsixTooling=true --self-contained=true
    
    # Find the msix file
    - name: STORE - Locate msix
      if: ${{matrix.target_audience}} == 'msstore'
      id: find-store-msix
      shell: pwsh
      run: |
        $msixPath = Get-ChildItem -Filter NoteTakingApp.Maui*.msix -Recurse | %{$_.FullName}
        echo "PACKAGE_PATH=$msixPath" >> $env:GITHUB_OUTPUT

    # Attaching the msix files to the GitHub artifacts for each build (this is not a GitHub release)
    - name: STORE - Attach artifacts
      if: ${{matrix.target_audience}} == 'msstore'
      uses: actions/upload-artifact@v4
      with:     
        name: "STORE_NoteTakingApp.Maui_v${{steps.version-creator.outputs.APP_VERSION}}.msix" 
        path: ${{steps.find-store-msix.outputs.PACKAGE_PATH}}
        if-no-files-found: error
        retention-days: 30

    - name: STORE - Cleanup build artifacts
      if: ${{matrix.target_audience}} == 'msstore'
      shell: pwsh
      run: Remove-Item * -Include *.msix -Recurse -Force

    # ----------------------------------------------------------- #
    #                   SIDELOAD MATRIX STEPS                     #
    #           if matrix.target_audience == 'sideload'           #
    # ----------------------------------------------------------- #

    # Update the app manifest using the sideload publisher identity
    - name: SIDELOAD - Update manifest for side load build
      if: ${{matrix.target_audience}} == 'sideload'
      run: |
        [xml]$manifest = get-content 'NoteTakingApp.Maui\Platforms\Windows\Package.appxmanifest'
        $manifest.Package.Identity.Version = "${{steps.version-creator.outputs.APP_VERSION}}"
        $manifest.Package.Identity.Name = 'scottware.NoteTaker'
        $manifest.Package.Identity.Publisher = 'CN="Lancelot Software, LLC", O="Lancelot Software, LLC", L=NORTH BILLERICA, S=Massachusetts, C=US'
        $manifest.Package.Properties.DisplayName = 'NoteTake_r'
        $manifest.Package.Properties.PublisherDisplayName = 'scottware'
        $manifest.Package.Applications.Application.VisualElements.DisplayName = 'NoteTake_r'
        $manifest.save("NoteTakingApp.Maui\Platforms\Windows\Package.appxmanifest")
    
    # CODESIGN OPTION 1 - Using a PFX to sign the msix file
    - name: SIDELOAD - Save certificate Base64 To .pfx file
      if: ${{matrix.target_audience}} == 'sideload'
      id: save-pfx-file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: "LancelotSoftwareLLC.pfx"
        fileDir: "${{github.workspace}}"
        encodedString: ${{secrets.CODESIGN_CERTIFICATE_BASE64}}

    # Compile and publish the WinUI project with codesigning enabled so it can be installed without the Microsoft Store
    - name: SIDELOAD - Build Maui WinUI project
      if: ${{matrix.target_audience}} == 'sideload'
      shell: pwsh
      run: dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f "${{env.TFM}}-windows10.0.19041.0" -p:RuntimeIdentifierOverride=win10-x64 -p:PublishTrimmed=False -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:EnableMsixTooling=true --self-contained=true -p:PackageCertificateKeyFile="${{steps.save-pfx-file.outputs.filePath}}" -p:PackageCertificatePassword="${{secrets.CODESIGN_CERTIFICATE_PASSWORD}}"

    # CODESIGN OPTION 2 - When you get your own Code Signing identity, we can sign the msix file much easier
    # # Login to Azure CLI
    # # No secrets needed! This will use the GitHub OIDC token to authenticate.
    # - name: SIDELOAD - Azure login using OIDC via GitHub
    #   uses: azure/login@v2
    #   id: azlogin
    #   with:
    #     client-id: "32daa13b-f4bb-4809-8ef6-58cb39051acd"
    #     tenant-id: "bd47e796-3473-4b8a-9101-1f4c0c7af31a"
    #     subscription-id: "48ab4839-62af-4ab3-afe6-043ea4d7c137"
    #
    # - name: SIDELOAD - Sign files with Trusted Signing
    #   uses: azure/trusted-signing-action@v0.4.0
    #   with:
    #     endpoint: https://eus.codesigning.azure.net/
    #     trusted-signing-account-name: PrimaryCodeSign
    #     certificate-profile-name: lancemccarthylivepublic
    #     timestamp-rfc3161: http://timestamp.acs.microsoft.com
    #     timestamp-digest: SHA256
    #     file-digest: SHA256
    #     files-folder: ${{github.workspace}}\NoteTakingApp.Maui\bin\Release\net8.0-windows10.0.19041.0\
    #     files-folder-recurse: true
    #     files-folder-depth: 4
    #     files-folder-filter: msix, msixbundle
    #     exclude-azure-cli-credential: false
    #     exclude-environment-credential: true
    #     exclude-workload-identity-credential: true
    #     exclude-managed-identity-credential: true
    #     exclude-shared-token-cache-credential: true
    #     exclude-visual-studio-credential: true
    #     exclude-visual-studio-code-credential: true
    #     exclude-azure-powershell-credential: true
    #     exclude-azure-developer-cli-credential: true
    #     exclude-interactive-browser-credential: true
    #
    # - name: SIDELOAD - Build Maui WinUI project
    #   if: ${{matrix.target_audience}} == 'sideload'
    #   shell: pwsh
    #   run: dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIG}} -f "${{env.TFM}}-windows10.0.19041.0" -p:RuntimeIdentifierOverride=win10-x64 -p:PublishTrimmed=False -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=false -p:EnableMsixTooling=true --self-contained=true
    
    # Find the msix file
    - name: SIDELOAD - Locate msix
      if: ${{matrix.target_audience}} == 'sideload'
      id: find-sideload-msix
      shell: pwsh
      run: |
        $msixPath = Get-ChildItem -Filter NoteTakingApp.Maui*.msix -Recurse | %{$_.FullName}
        echo "PACKAGE_PATH=$msixPath" >> $env:GITHUB_OUTPUT

    - name: SIDELOAD - Attach artifacts
      if: ${{matrix.target_audience}} == 'sideload'
      uses: actions/upload-artifact@v4
      with:     
        name: "SIDELOAD_NoteTakingApp.Maui_v${{steps.version-creator.outputs.APP_VERSION}}.msix" 
        path: ${{steps.find-sideload-msix.outputs.PACKAGE_PATH}}
        if-no-files-found: error
        retention-days: 30

    # Create a GitHub Release with the msix file(s) attached
    - name: SIDELOAD - Create GitHub Release
      if: ${{matrix.target_audience}} == 'sideload'
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        name: "NoteTakingApp.Maui v.${{steps.version-creator.outputs.APP_VERSION}}"
        tag_name: "v${{steps.version-creator.outputs.APP_VERSION}}"
        body: "This is v.${{steps.version-creator.outputs.APP_VERSION}} of the xkcd viewer app. To install, download and run the .msix installer file."
        files: ${{steps.find-msix.outputs.PACKAGE_PATH}}

    - name: SIDELOAD - Cleanup build artifacts
      if: ${{matrix.target_audience}} == 'sideload'
      shell: pwsh
      run: Remove-Item * -Include *.msix -Recurse -Force

# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  maui-android:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Generate version number using date and run number
      shell: pwsh
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
        echo "APP_VERSION=$ver" >> $GITHUB_OUTPUT

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      shell: pwsh
      run: dotnet restore ${{ env.PROJECT_PATH }} --configfile ${{ env.NUGETCONFIG_PATH }}

    - name: Build Maui Android project
      shell: pwsh
      run: dotnet build ${{ env.PROJECT_PATH }} -c Debug -f net8.0-android -p:PublishTrimmed=False

# ************************* #
# >>>>>>> iOS Build <<<<<<< #
# ************************* #
  maui-ios:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #- uses: maxim-lobanov/setup-xcode@v1
    #  with:
    #    xcode-version: latest

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Generate version number using date and run number
      id: version-creator
      shell: bash
      run: |
        buildDay=`date +%Y.%m%d`
        echo $buildDay
        ver="${buildDay}.${GITHUB_RUN_NUMBER}.0"
        echo $ver
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      shell: bash
      run: dotnet restore ${{ env.PROJECT_PATH }} --configfile ${{ env.NUGETCONFIG_PATH }}

    - name: Build MAUI iOS project
      shell: bash
      run: dotnet build ${{ env.PROJECT_PATH }} -c Debug -f net8.0-ios -p:PublishTrimmed=True -p:MtouchLink=SdkOnly


# ********************************* #
# >>>>>>> MacCatalyst Build <<<<<<< #
# ********************************* #
  maui-macos:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #- uses: maxim-lobanov/setup-xcode@v1
    #  with:
    #    xcode-version: latest

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Generate version number using date and run number
      id: version-creator
      shell: bash
      run: |
        buildDay=`date +%Y.%m%d`
        echo $buildDay
        ver="${buildDay}.${GITHUB_RUN_NUMBER}.0"
        echo $ver
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages
      shell: bash
      run: dotnet restore ${{ env.PROJECT_PATH }} --configfile ${{ env.NUGETCONFIG_PATH }}
    
    - name: Build MAUI MacCatalyst project
      shell: bash
      run: dotnet build ${{ env.PROJECT_PATH }} -f net8.0-maccatalyst -c Debug -p:PublishTrimmed=True -p:MtouchLink=SdkOnly